

all:
	g++  -o animGL.exe MolecDynOpenGLAnim.cpp -fopenmp -I../include -lm -lGL -lGLU -lglut -lXi -lXmu -L/home/konrad/CProjects/kms-project1/lib -Wl,-R/home/konrad/CProjects/kms-project1/lib -lmolecdyn -O3